# -*- coding: utf-8 -*-
"""Reconhecimento-facial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkV2qpgGNr_rDJHO-BEV8fXPxpah9P_g
"""

from google.colab import drive
drive.mount('/content/drive')

# Instalação das bibliotecas necessárias
!pip install tensorflow matplotlib

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

# Configurações
data_dir = '/content/drive/MyDrive/Colab Notebooks/dataset'  # Altere para o caminho correto do seu diretório
IMG_HEIGHT = 180
IMG_WIDTH = 180
BATCH_SIZE = 32

# Gerador de imagens com aumento de dados
train_datagen = ImageDataGenerator(
    rescale=1.0/255.0,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Carregar as imagens
train_data = train_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='binary'  # Use 'categorical' se houver mais de 2 classes
)

# Construir o modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Use 'softmax' se houver mais de 2 classes
])

# Compilar o modelo
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Treinar o modelo
history = model.fit(train_data, epochs=10)

# Exibir gráfico de precisão
plt.plot(history.history['accuracy'], label='Precisão de Treinamento')
plt.title('Precisão de Treinamento')
plt.xlabel('Épocas')
plt.ylabel('Precisão')
plt.legend()
plt.show()

# Salvar o modelo
model.save('walter_jesse_model.h5')

# Instalar bibliotecas necessárias
!pip install ultralytics tensorflow matplotlib opencv-python-headless

from ultralytics import YOLO
import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing import image

# Carregar o modelo YOLO para detecção de rosto
yolo_model = YOLO('yolov8n.pt')

# Carregar o modelo de classificação
classifier_model = tf.keras.models.load_model('walter_jesse_model.h5')

# Dimensões para o redimensionamento (conforme o modelo)
IMG_HEIGHT = 180
IMG_WIDTH = 180

# Função para preprocessar o rosto
def preprocess_face(face_img):
    face_img = cv2.resize(face_img, (IMG_HEIGHT, IMG_WIDTH))  # Redimensionar
    face_img = np.expand_dims(face_img, axis=0) / 255.0  # Normalizar
    return face_img

# Caminho para a imagem de teste
test_image_path = '/content/drive/MyDrive/Colab Notebooks/teste3.jpg'

# Realizar a detecção de rostos na imagem
results = yolo_model(test_image_path)

# Carregar a imagem original
image = cv2.imread(test_image_path)

# Processar cada rosto detectado com confiança acima de um limite
confidence_threshold = 0.5  # Ajuste para filtrar apenas rostos de alta confiança

for box in results[0].boxes:
    if box.conf[0] < confidence_threshold:
        continue  # Ignorar detecções com baixa confiança

    x1, y1, x2, y2 = map(int, box.xyxy[0])  # Coordenadas do rosto detectado

    # Extrair a região do rosto da imagem
    face = image[y1:y2, x1:x2]

    # Preprocessar o rosto para o modelo de classificação
    preprocessed_face = preprocess_face(face)

    # Realizar a predição para identificar o personagem
    predictions = classifier_model.predict(preprocessed_face)
    label = "Walter White" if predictions[0] > 0.5 else "Jesse Pinkman"

    # Adicionar retângulo e rótulo ao redor do rosto
    color = (0, 255, 0) if label == "Walter White" else (255, 0, 0)
    cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
    cv2.putText(image, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

# Salvar e exibir a imagem resultante
output_image_path = '/content/image_with_names.jpg'
cv2.imwrite(output_image_path, image)

# Exibir a imagem completa com os rótulos aplicados apenas aos rostos
image_with_names = mpimg.imread(output_image_path)
plt.imshow(image_with_names)
plt.axis('off')
plt.show()